name: Scrape

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - name: "Run Scraper"
        run: npm run scrape

      - name: "Upload Data to Repo"
        run: |
          git config user.name "scraper"
          git config user.email "scraper"
          git add .
          git commit -m "Upload scraped Data to Repo #${{ github.run_id }}" || exit 0
          git push